export const FETCH_COUNTRY_REQUEST = 'FETCH_COUNTRY_REQUEST';
export const FETCH_COUNTRY_SUCCESS = 'FETCH_COUNTRY_SUCCESS';
export const FETCH_COUNTRY_FAILED = 'FETCH_COUNTRY_FAILED';

export const SORT_COUNTRY_ASC = 'SORT_COUNTRY_ASC';
export const SORT_COUNTRY_DESC = 'SORT_COUNTRY_DESC';

export const SEARCH_COUNTRY = 'SEARCH_COUNTRY';